Resources/book_catalog/app/catalog/models.py
from app import db  # from the app package __init__
from datetime import datetime


# PUBLICATION TABLE
class Publication(db.Model):
    __tablename__ = 'publication'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return 'The Publisher is {}'.format(self.name)


# BOOKS TABLE
class Book(db.Model):
    __tablename__ = 'book'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(500), nullable=False, index=True)
    author = db.Column(db.String(350))
    avg_rating = db.Column(db.Float)
    format = db.Column(db.String(50))
    image = db.Column(db.String(100), unique=True)
    num_pages = db.Column(db.Integer)
    pub_date = db.Column(db.DateTime, default=datetime.utcnow())

    # ESTABLISH RELATIONSHIP
    pub_id = db.Column(db.Integer, db.ForeignKey('publication.id'))

    def __init__(self, title, author, avg_rating, book_format, image, num_pages, pub_id):
        self.title = title
        self.author = author
        self.avg_rating = avg_rating
        self.format = book_format
        self.image = image
        self.num_pages = num_pages
        self.pub_id = pub_id

    def __repr__(self):
        return '{} by {}'.format(self.title, self.author)

Resources/book_catalog/app/catalog/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates')
from app.catalog import routes, models  # to avoid circular imports

Resources/book_catalog/app/catalog/routes.py
from app.catalog import main
from app import db
from app.catalog.models import Book, Publication
from flask import render_template


@main.route('/')
def display_books():
    books = Book.query.all()
    return render_template('home.html', books=books)


@main.route('/display/publisher/<publisher_id>')
def display_publisher(publisher_id):
    publisher = Publication.query.filter_by(id=publisher_id).first()
    publisher_books = Book.query.filter_by(pub_id = publisher.id).all()

    return render_template('publisher.html', publisher=publisher, publisher_books=publisher_books)

Resources/book_catalog/app/catalog/templates/home.html
{% extends 'layout.html' %}


{% block content %}
    <div class="container books">
        <div class="row">
        {% for book in books %}
            <div class="col-md-4">
                <img src="static/img/{{ book.image }}" alt="book-img" height="200" width="190" class="img-rounded">
                <h4> Title: {{ book.title }} </h4>
                <p> Authors: {{ book.author }} </p>
                <p> Format: {{ book.format }} </p>
                <p> Average Rating: {{ book.avg_rating }} </p>
                <p> Pages: {{ book.num_pages }} </p>
                <p><a href="{{ url_for('main.display_publisher', publisher_id=book.pub_id) }}">Publisher ID: {{ book.pub_id }}
                </a></p>
                <br>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock content %}

Resources/book_catalog/app/catalog/templates/layout.html
<!DOCTYPE html>
<html lang="en">

    {# head #}
    {% block head %}
        <head>
            <title> books Inc </title>
            <meta charset="UTF-8">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <link href="https://fonts.googleapis.com/css?family=Sansita" rel="stylesheet">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
        </head>
    {% endblock head %}

    {# body #}
    {% block body %}
    <body>
    <div class="wrapper">
        {# navigation bar #}
        {% block navbar %}
        <nav class="navbar navbar-inverse">
            <div class="container">
                <a class="navbar-brand title" href="{{ url_for('main.display_books') }}">Book Shop Around the Corner</a>

                <ul class="nav navbar-nav pull-right nav-list">
                    <li><a href=""> Home </a></li>
                    <li><a href=""> Register </a></li>
                    <li><a href=""> SignIn </a></li>
                </ul>
            </div>
        </nav>
        {% endblock navbar %}

        {# empty block for custom content #}
        {% block content %} {% endblock content %}

        {# footer #}
        {% block footer %}
        <footer>
            <div class="container ftr">
                <hr>
                <p class="text-center small"> The Shop Around The Corner &copy;	| 2019 </p>
            </div>
        </footer>
        {% endblock footer %}

    </div>
    </body>
    {% endblock body %}
</html>

Resources/book_catalog/app/catalog/templates/publisher.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container publisher">
        <h4> Books by {{ publisher.name }} </h4>
        <hr><br>
        <ol>
            {% for book in publisher_books %}
                <li type="1">
                    {{ book.title }} by {{ book.author }}
                </li>
            {% endfor %}
        </ol>
    </div>
{% endblock content %}